docRoot                   /usr/local/lsws/Example/html
vhDomain                  autoseoservices.com
vhAliases                 www.autoseoservices.com
adminEmails               info@usbrandbooster.com

enableGzip                1
enableIpGeo               1

################################
# LOGS
################################

errorlog $VH_ROOT/logs/$VH_NAME.error_log {
  useServer               0
  logLevel                WARN
  rollingSize             10M
}

accesslog $VH_ROOT/logs/$VH_NAME.access_log {
  useServer               0
  logFormat               "%h %l %u %t \"%r\" %>s %b"
  rollingSize             10M
}

################################
# EXTERNAL APPS
################################

extprocessor frontend {
  type                    proxy
  address                 127.0.0.1:3030
  maxConns                200
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  autoStart               0
}

extprocessor backend {
  type                    proxy
  address                 127.0.0.1:5050
  maxConns                200
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      5
  respBuffer              0
  autoStart               0
}

################################
# CONTEXTS
################################

context / {
  type                    proxy
  handler                 frontend
  addDefaultCharset       off
}

context /api {
  type                    proxy
  handler                 backend
  addDefaultCharset       off
}

################################
# INDEX
################################

index {
  useServer               0
  indexFiles              index.html
  autoIndex               0
}

################################
# SSL
################################

vhssl {
  keyFile                 /etc/letsencrypt/live/autoseoservices.com/privkey.pem
  certFile                /etc/letsencrypt/live/autoseoservices.com/fullchain.pem
  certChain               1
}

################################
# ACME CHALLENGE
################################

context /.well-known/acme-challenge {
  location                /usr/local/lsws/Example/html/.well-known/acme-challenge
  allowBrowse             1
  rewrite  {
     enable                  0
  }
  addDefaultCharset       off
  phpIniOverride  {
  }
}
