import React, { useState, useEffect } from 'react';
import Layout from '../components/Layout';
import { User, DocumentData, DocumentStatus } from '../types';
import { createDocument, getDocuments } from '../services/storage';
import { generateBasePdf } from '../services/pdfService';
import { Plus, Send, Copy, FileCheck, User as UserIcon, Briefcase, FileText, Trash, Settings, Upload, Image as ImageIcon, Save, AlertTriangle } from 'lucide-react'; // Added icons
import { DocumentsAPI, AuthAPI } from '../services/api'; // Added AuthAPI
import AgreementTemplates, { AgreementTemplate, availableTemplates } from '../components/AgreementTemplates';

interface Props {
  user: User;
  onLogout: () => void;
}

export default function AgentDashboard({ user, onLogout }: Props) {
  const [localUser, setLocalUser] = useState<User>(user); // Local copy of user for profile updates
  const [docs, setDocs] = useState<any[]>([]);
  const [view, setView] = useState<'list' | 'create' | 'settings'>('list'); // Added 'settings' view
  const [activeTab, setActiveTab] = useState<'template' | 'client' | 'project' | 'agency' | 'services'>('template');
  const [selectedTemplate, setSelectedTemplate] = useState<AgreementTemplate | null>(null);

  // Form State
  const [formData, setFormData] = useState({
    // Document Meta
    title: '',

    // Client Info
    clientName: '',
    clientCompany: '',
    clientEmail: '',
    clientPhone: '',
    clientAddress: '',
    clientCityStateZip: '',
    clientCountry: '',

    // Project Info
    projectName: '',
    startDate: '',
    endDate: '',
    scopeOfWork: '',
    paymentTerms: '',
    specialNotes: '',

    // Agency Info
    agencyName: 'SignFlow Agency',
    agencyEmail: 'info@usbrandbooster.com',
    agencyPhone: '',

    // Template-specific fields (US Brand Booster)
    clientCompanyName: '',
    businessOwnerName: '',
    clientDomain: '',
    upfrontPayment: '350',
    remainingPayment: '650',
    serviceOverviewDetails: `- Tailored Content: Unique content aligned with your business nature and target audience.
- Geographic Targeting: Optimize Google Guarantee for specific cities of your choice, expanding your local reach – rely on chosen list of zip codes of the supplied services. The customer will supply a list.
- Complete Website (10 Page website): Standard set of the pages and the galleries of the services on top.
- ROI Reports: Receive monthly reports on the return on investment (ROI) generated by the US BB marketing efforts. Partner with US BB on a flexible, transparent basis with no contracts or hidden fees.`,
    servicesInScopeDetails: `- Create the Mockup pages for the Commercial Remodeling Contractors verification and approval. Supply 3 reviews before uploading the live pages to the Web.
- US BB will assist in creating the Google Business account.
- As soon as the Web-Site is created a 3 months Web SEO free service will start
- The US BB and the Commercial Remodeling Contractors should agree on the monthly payment for the following services:
- Facebook Maintenance and support, like posts and pictures upload activities
- Instagram – uploading the pictures and videos
- Web-site pictures and videos uploads
- Changing the keywords every period of time.
- Creating the landing pages on the Commercial Remodeling Contractors domain
- US BB will create a Facebook Dedicated page and apply the ownership to Commercial Remodeling Contractors. US BB will create 1000 facebook followers
- US BB will create the Instagram dedicated account for Commercial Remodeling Contractors. US BB will create 1300 insta followers + 1 month social media. After 1 month social media platforms will be charged.
- The US BB will upload any pictures and videos related to construction supplied by the Commercial Remodeling Contractors to Website, Facebook, Instagram.
- All the Credentials of all the accounts will be defined with the agreement by the Commercial Remodeling Contractors, including the usernames and passwords.`,
  });

  const [creating, setCreating] = useState(false);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);
  const [isCopyModalOpen, setIsCopyModalOpen] = useState(false);
  const [isResentModalOpen, setIsResentModalOpen] = useState(false);

  const load = async () => {
    try {
      const resp = await DocumentsAPI.list();
      const serverDocs = resp.documents || [];
      const ownerId = String(localUser.id);
      const ownedServerDocs = serverDocs.filter((d: any) => {
        const docAgentId = String(d.agentId || '');
        const metaAgentId = String(d?.metadata?.agentId || '');
        return docAgentId === ownerId || metaAgentId === ownerId;
      });
      setDocs(
        ownedServerDocs
          .sort((a: any, b: any) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())
      );
    } catch (e) {
      console.error('[AgentDashboard] load() failed', e);
      setDocs([]);
    }
  };

  useEffect(() => {
    load();
    const onFocus = () => load();
    window.addEventListener('focus', onFocus);
    const interval = setInterval(load, 10000); // poll every 10s
    return () => {
      window.removeEventListener('focus', onFocus);
      clearInterval(interval);
    };
  }, [user.id, view]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const validateForm = () => {
    if (!formData.clientEmail.endsWith('@gmail.com')) {
      alert('Client email must be a valid @gmail.com address for secure signing.');
      return false;
    }
    if (!formData.title || !formData.clientName || !formData.projectName) {
      alert('Please fill in required fields (Title, Client Name, Project Name)');
      return false;
    }
    return true;
  };

  const handleCreateDocument = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;
    setCreating(true);

    try {
      // 1. Generate PDF Base64
      const result = await generateBasePdf({
        ...formData,
        agentId: localUser.id,
        agentName: localUser.name,
        agentSignature: localUser.signature, // Pass signature
      });
      const pdfBase64 = result.pdf;

      // 2. Create on backend
      const payload: any = {
        title: formData.title,
        description: formData.scopeOfWork || undefined,
        fileUrl: pdfBase64,
        // clientId omitted -> backend will find/create by email
        metadata: {
          agentId: localUser.id,
          agentName: localUser.name,
          agentSignature: localUser.signature,
          clientName: formData.clientName,
          clientEmail: formData.clientEmail,
          clientCompany: formData.clientCompany,
          clientPhone: formData.clientPhone,
          clientAddress: formData.clientAddress,
          projectName: formData.projectName,
          startDate: formData.startDate || undefined,
          endDate: formData.endDate || undefined,
          scopeOfWork: formData.scopeOfWork || undefined,
          paymentTerms: formData.paymentTerms || undefined,
          specialNotes: formData.specialNotes || undefined,
          agencyName: formData.agencyName,
          agencyEmail: formData.agencyEmail,
          agencyPhone: formData.agencyPhone || undefined,
          // Template information
          templateId: selectedTemplate?.id || undefined,
          templateName: selectedTemplate?.name || undefined,
          // Template-specific fields (US Brand Booster)
          clientCompanyName: formData.clientCompanyName || undefined,
          businessOwnerName: formData.businessOwnerName || undefined,
          clientDomain: formData.clientDomain || undefined,
          upfrontPayment: formData.upfrontPayment || undefined,
          remainingPayment: formData.remainingPayment || undefined,
          serviceOverviewDetails: formData.serviceOverviewDetails || undefined,
          servicesInScopeDetails: formData.servicesInScopeDetails || undefined,
        }
      };

      const resp = await DocumentsAPI.create(payload);
      const created = resp.document;

      // 3. Update state from backend
      setDocs([created, ...docs]);
      setView('list');

      // Reset form to defaults
      setFormData({
        title: '',
        clientName: '',
        clientCompany: '',
        clientEmail: '',
        clientPhone: '',
        clientAddress: '',
        clientCityStateZip: '',
        clientCountry: '',
        projectName: '',
        startDate: '',
        endDate: '',
        scopeOfWork: '',
        paymentTerms: '',
        specialNotes: '',
        agencyName: 'SignFlow Agency',
        agencyEmail: 'info@usbrandbooster.com',
        agencyPhone: '',
        clientCompanyName: '',
        businessOwnerName: '',
        clientDomain: '',
        upfrontPayment: '350',
        remainingPayment: '650',
      });
      setSelectedTemplate(null);
      setActiveTab('template');
    } catch (err) {
      console.error(err);
      alert("Error creating document. Please try again.");
    } finally {
      setCreating(false);
    }
  };

  const copyLink = async (docOrId: any) => {
    const backendId = String(typeof docOrId === 'string' ? docOrId : (docOrId._id || docOrId.id));
    let token = typeof docOrId === 'string' ? undefined : docOrId.signToken;
    // If token missing, try to refetch document; if still missing, trigger resend to generate a new token
    if (!token && backendId) {
      try {
        const resp = await DocumentsAPI.get(backendId);
        token = resp?.document?.signToken;
        if (!token) {
          await DocumentsAPI.resend(backendId);
          const after = await DocumentsAPI.get(backendId);
          token = after?.document?.signToken;
        }
      } catch { }
    }
    const base = `${window.location.origin}${window.location.pathname}#/sign/${backendId}`;
    const url = token ? `${base}?token=${token}` : base;
    navigator.clipboard.writeText(url);
    setCopiedLink(url);
    setIsCopyModalOpen(true);
  };

  const resendLink = async (doc: DocumentData) => {
    try {
      const backendId = String((doc as any)._id || (doc as any).id);
      await DocumentsAPI.resend(backendId);
      setIsResentModalOpen(true);
    } catch (e: any) {
      alert(`Failed to resend link: ${e?.message || 'Unknown error'}`);
    }
  };

  // Profile / Settings Logic
  const [tempSignature, setTempSignature] = useState<string>('');
  const [isUploading, setIsUploading] = useState(false);

  useEffect(() => {
    if (view === 'settings' && localUser.signature) {
      setTempSignature(localUser.signature);
    }
  }, [view, localUser.signature]);

  const handleSignatureUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate size (e.g. max 2MB)
    if (file.size > 2 * 1024 * 1024) {
      alert('File size must be less than 2MB');
      return;
    }

    const reader = new FileReader();
    reader.onload = (evt) => {
      const result = evt.target?.result as string;

      // Validate dimensions
      const img = new Image();
      img.onload = () => {
        if (img.width < 100 || img.height < 50) {
          alert('Image resolution is too low. Please upload a larger image.');
          return;
        }
        const ratio = img.width / img.height;
        if (ratio < 1 || ratio > 10) {
          alert('Image aspect ratio is unusual (too tall or too wide). please use an image that is roughly 3:1 or 4:1 width to height.');
          return;
        }
        setTempSignature(result);
      };
      img.onerror = () => {
        alert('Invalid image file.');
      };
      img.src = result;
    };
    reader.readAsDataURL(file);
  };

  const saveProfile = async () => {
    setIsUploading(true);
    try {
      await AuthAPI.updateProfile({ signature: tempSignature });
      setLocalUser({ ...localUser, signature: tempSignature });
      alert('Profile updated successfully!');
      setView('list');
    } catch (e: any) {
      alert(`Failed to save profile: ${e?.message}`);
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <Layout user={user} onLogout={onLogout} title="Support Workspace">

      {view === 'list' && (
        <div className="space-y-6">
          <div className="flex justify-between items-center">
            <h3 className="text-lg font-medium text-brand-900">Your Documents</h3>
            <div className="flex items-center gap-2">
              <button
                onClick={load}
                className="px-3 py-2 rounded border border-brand-200 text-sm hover:bg-brand-50"
              >
                Refresh
              </button>
              <button
                onClick={() => setView('create')}
                className="bg-yellow-400 text-brand-900 px-4 py-2 rounded-lg shadow-sm hover:bg-yellow-300 flex items-center gap-2"
              >
                <Plus size={18} /> Create New Document
              </button>
              <button
                onClick={() => setView('settings')}
                className="bg-white text-brand-700 border border-brand-200 px-4 py-2 rounded-lg shadow-sm hover:bg-brand-50 flex items-center gap-2"
              >
                <Settings size={18} /> Settings
              </button>
            </div>
          </div>

          <div className="bg-white shadow-sm rounded-lg border border-brand-100 overflow-hidden">
            <table className="min-w-full divide-y divide-brand-100">
              <thead className="bg-brand-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-brand-500 uppercase tracking-wider">Document</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-brand-500 uppercase tracking-wider">Client</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-brand-500 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-brand-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-brand-100">
                {docs.map((doc: any) => (
                  <tr key={doc._id || doc.id}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm font-medium text-brand-900">{doc.title}</div>
                      <div className="text-xs text-brand-500">{doc.projectName || doc?.metadata?.projectName}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="text-sm text-brand-900">{doc.clientName || doc?.metadata?.clientName}</div>
                      <div className="text-xs text-brand-500">{doc.clientEmail || doc?.metadata?.clientEmail}</div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${String(doc.status).toLowerCase() === 'signed' ? 'bg-brand-800 text-yellow-300' : 'bg-yellow-100 text-yellow-800'}`}>
                        {doc.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium flex gap-4">
                      <>
                        <button onClick={() => copyLink(doc)} className="text-yellow-600 hover:text-yellow-500 flex items-center gap-1">
                          <Copy size={16} /> Copy Link
                        </button>
                        {String(doc.status).toLowerCase() !== 'signed' && (
                          <button onClick={() => resendLink(doc)} className="text-blue-600 hover:text-blue-900 flex items-center gap-1">
                            <Send size={16} /> Resend Link
                          </button>
                        )}

      {isResentModalOpen && (
        <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/40 whitespace-normal">
          <div className="bg-white rounded-lg shadow-xl max-w-md w-full mx-4">
            <div className="px-6 py-4 border-b flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-blue-100 text-blue-600">
                <Send size={20} />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Signing link resent</h3>
                <p className="text-xs text-gray-500 break-words">If SMTP is configured, the client will receive an email with the updated signing link.</p>
              </div>
            </div>
            <div className="px-6 py-4 bg-gray-50 flex justify-end">
              <button
                type="button"
                className="px-4 py-2 text-sm rounded-md bg-emerald-600 text-white hover:bg-emerald-700"
                onClick={() => setIsResentModalOpen(false)}
              >
                OK
              </button>
            </div>
          </div>
        </div>
      )}

      {isCopyModalOpen && (
        <div className="fixed inset-0 z-40 flex items-center justify-center bg-black/40 whitespace-normal">
          <div className="bg-white rounded-lg shadow-xl max-w-lg w-full mx-4">
            <div className="px-6 py-4 border-b flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-emerald-100 text-emerald-600">
                <Copy size={20} />
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900">Signing link copied</h3>
                <p className="text-xs text-gray-500">You can paste this link into an email, chat, or message to your client.</p>
              </div>
            </div>
            <div className="px-6 py-4 text-sm text-gray-700 space-y-3">
              <div className="rounded-md bg-gray-50 px-3 py-2 border border-gray-200 text-xs break-all font-mono text-gray-700 max-w-full overflow-x-auto">
                <span className="break-all">{copiedLink}</span>
              </div>
            </div>
            <div className="px-6 py-4 bg-gray-50 flex justify-end">
              <button
                type="button"
                className="px-4 py-2 text-sm rounded-md bg-emerald-600 text-white hover:bg-emerald-700"
                onClick={() => {
                  setIsCopyModalOpen(false);
                  setCopiedLink(null);
                }}
              >
                OK
              </button>
            </div>
          </div>
        </div>
      )}
                        {String(doc.status).toLowerCase() === 'signed' ? (
                          <a
                            href={doc.signedPdfUrl ? `data:application/pdf;base64,${doc.signedPdfUrl}` : undefined}
                            download={`${doc.title}-signed.pdf`}
                            className="text-green-600 hover:text-green-900 flex items-center gap-1"
                          >
                            <FileCheck size={16} /> Download
                          </a>
                        ) : null}
                      </>
                    </td>
                  </tr>
                ))}
                {docs.length === 0 && (
                  <tr><td colSpan={4} className="px-6 py-4 text-center text-gray-500">No documents created yet.</td></tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      )}
      {
        view === 'create' && (
          <div className="max-w-4xl mx-auto">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-gray-900">Create Agreement</h3>
              <button onClick={() => setView('list')} className="text-gray-500 hover:text-gray-700">Cancel</button>
            </div>

            <div className="bg-white shadow rounded-lg overflow-hidden flex flex-col md:flex-row">
              {/* Sidebar Tabs */}
              <div className="w-full md:w-64 bg-gray-50 border-r border-gray-200 p-4 flex flex-col gap-2">
                <button
                  onClick={() => setActiveTab('template')}
                  className={`flex items-center gap-2 px-4 py-3 rounded-md text-sm font-medium transition-colors ${activeTab === 'template' ? 'bg-brand-100 text-brand-700' : 'text-gray-600 hover:bg-gray-100'}`}
                >
                  <FileText size={18} /> Agreement Template
                </button>
                <button
                  onClick={() => setActiveTab('services')}
                  className={`flex items-center gap-2 px-4 py-3 rounded-md text-sm font-medium transition-colors ${activeTab === 'services' ? 'bg-brand-100 text-brand-700' : 'text-gray-600 hover:bg-gray-100'}`}
                  disabled={!selectedTemplate}
                >
                  <FileText size={18} /> Service Details
                </button>
                <button
                  onClick={() => setActiveTab('client')}
                  className={`flex items-center gap-2 px-4 py-3 rounded-md text-sm font-medium transition-colors ${activeTab === 'client' ? 'bg-brand-100 text-brand-700' : 'text-gray-600 hover:bg-gray-100'}`}
                >
                  <UserIcon size={18} /> Client Information
                </button>
                <button
                  onClick={() => setActiveTab('project')}
                  className={`flex items-center gap-2 px-4 py-3 rounded-md text-sm font-medium transition-colors ${activeTab === 'project' ? 'bg-brand-100 text-brand-700' : 'text-gray-600 hover:bg-gray-100'}`}
                >
                  <FileText size={18} /> Project Details
                </button>
                <button
                  onClick={() => setActiveTab('agency')}
                  className={`flex items-center gap-2 px-4 py-3 rounded-md text-sm font-medium transition-colors ${activeTab === 'agency' ? 'bg-brand-100 text-brand-700' : 'text-gray-600 hover:bg-gray-100'}`}
                >
                  <Briefcase size={18} /> Agency Info
                </button>
              </div>

              {/* Form Content */}
              <div className="flex-1 p-6">
                <form onSubmit={handleCreateDocument} className="space-y-6">

                  {activeTab === 'template' && (
                    <div className="space-y-4 animate-fadeIn">
                      <AgreementTemplates
                        selectedTemplate={selectedTemplate}
                        onSelectTemplate={(template) => {
                          setSelectedTemplate(template);
                          // Auto-fill title if template is selected
                          if (template && !formData.title) {
                            setFormData({ ...formData, title: template.name });
                          }
                        }}
                      />

                      {selectedTemplate && selectedTemplate.id === 'us-brand-booster' && (
                        <div className="mt-6 space-y-4">
                          <h4 className="text-lg font-medium border-b pb-2">Template-Specific Fields</h4>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="md:col-span-2">
                              <label className="block text-sm font-medium text-gray-700">Client Company Name *</label>
                              <input
                                name="clientCompanyName"
                                required
                                value={formData.clientCompanyName}
                                onChange={handleInputChange}
                                placeholder="e.g. Commercial Remodeling Contractors"
                                className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm"
                              />
                            </div>
                            <div className="md:col-span-2">
                              <label className="block text-sm font-medium text-gray-700">Business Owner Name *</label>
                              <input
                                name="businessOwnerName"
                                required
                                value={formData.businessOwnerName}
                                onChange={handleInputChange}
                                placeholder="e.g. David Rozenstein"
                                className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm"
                              />
                            </div>
                            <div className="md:col-span-2">
                              <label className="block text-sm font-medium text-gray-700">Client Domain Name *</label>
                              <input
                                name="clientDomain"
                                required
                                value={formData.clientDomain}
                                onChange={handleInputChange}
                                placeholder="e.g. commercialremodelingcontractors.com"
                                className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm"
                              />
                            </div>
                            <div>
                              <label className="block text-sm font-medium text-gray-700">Upfront Payment ($) *</label>
                              <input
                                name="upfrontPayment"
                                type="number"
                                required
                                value={formData.upfrontPayment}
                                onChange={handleInputChange}
                                placeholder="350"
                                className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm"
                              />
                            </div>
                            <div>
                              <label className="block text-sm font-medium text-gray-700">Remaining Payment ($) *</label>
                              <input
                                name="remainingPayment"
                                type="number"
                                required
                                value={formData.remainingPayment}
                                onChange={handleInputChange}
                                placeholder="650"
                                className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm"
                              />
                            </div>
                          </div>
                        </div>
                      )}

                      <div className="flex justify-end pt-4">
                        <button
                          type="button"
                          onClick={() => setActiveTab('services')}
                          className="px-4 py-2 bg-gray-800 text-white rounded hover:bg-gray-700"
                          disabled={!selectedTemplate}
                        >
                          Next: Service Details
                        </button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'services' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Service Details</h4>
                      <p className="text-sm text-gray-500 mb-4">Edit the bullet points below. Each line will be treated as a bullet point in the generated PDF.</p>

                      <div>
                        <label className="block text-sm font-medium text-gray-700">Service Overview</label>
                        <textarea
                          name="serviceOverviewDetails"
                          rows={8}
                          value={formData.serviceOverviewDetails}
                          onChange={handleInputChange}
                          className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm font-mono"
                          placeholder="- Item: Description"
                        />
                      </div>

                      <div>
                        <label className="block text-sm font-medium text-gray-700">Services in Scope</label>
                        <textarea
                          name="servicesInScopeDetails"
                          rows={8}
                          value={formData.servicesInScopeDetails}
                          onChange={handleInputChange}
                          className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm font-mono"
                          placeholder="- Item description"
                        />
                      </div>

                      <div className="flex justify-end pt-4">
                        <button
                          type="button"
                          onClick={() => setActiveTab('client')}
                          className="px-4 py-2 bg-gray-800 text-white rounded hover:bg-gray-700"
                        >
                          Next: Client Information
                        </button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'client' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Client Information</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Full Name *</label>
                          <input name="clientName" required value={formData.clientName} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Company Name</label>
                          <input name="clientCompany" value={formData.clientCompany} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Gmail Address (Required) *</label>
                          <input name="clientEmail" type="email" required value={formData.clientEmail} onChange={handleInputChange} placeholder="example@gmail.com" className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Phone Number</label>
                          <input name="clientPhone" value={formData.clientPhone} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700">Address</label>
                          <input name="clientAddress" value={formData.clientAddress} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">City / State / Zip</label>
                          <input name="clientCityStateZip" value={formData.clientCityStateZip} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Country</label>
                          <input name="clientCountry" value={formData.clientCountry} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                      </div>
                      <div className="flex justify-end pt-4">
                        <button type="button" onClick={() => setActiveTab('project')} className="px-4 py-2 bg-gray-800 text-white rounded hover:bg-gray-700">Next: Project Details</button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'project' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Project & Terms</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700">Document Title / Type *</label>
                          <input name="title" required value={formData.title} onChange={handleInputChange} placeholder="e.g. Service Agreement, NDA" className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700">Project Name *</label>
                          <input name="projectName" required value={formData.projectName} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Start Date</label>
                          <input name="startDate" type="date" value={formData.startDate} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">End / Delivery Date</label>
                          <input name="endDate" type="date" value={formData.endDate} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>

                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700">
                            Scope of Work / Description
                          </label>
                          <textarea name="scopeOfWork" rows={5} value={formData.scopeOfWork} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>

                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700">Payment Terms</label>
                          <textarea name="paymentTerms" rows={3} value={formData.paymentTerms} onChange={handleInputChange} placeholder="e.g. 50% upfront, 50% on completion" className="block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>

                        <div className="md:col-span-2">
                          <label className="block text-sm font-medium text-gray-700">Special Notes / Clauses</label>
                          <textarea name="specialNotes" rows={3} value={formData.specialNotes} onChange={handleInputChange} className="block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                      </div>
                      <div className="flex justify-end pt-4 gap-2">
                        <button type="button" onClick={() => setActiveTab('client')} className="px-4 py-2 text-gray-600 hover:text-gray-900">Back</button>
                        <button type="button" onClick={() => setActiveTab('agency')} className="px-4 py-2 bg-gray-800 text-white rounded hover:bg-gray-700">Next: Agency Info</button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'agency' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Agency Information</h4>
                      <div className="grid grid-cols-1 gap-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Agency / Company Name</label>
                          <input name="agencyName" value={formData.agencyName} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Agent Name</label>
                          <input disabled value={user.name} className="mt-1 block w-full border border-gray-200 bg-gray-50 rounded p-2 text-sm text-gray-500" />
                          <span className="text-xs text-gray-400">Auto-filled from login</span>
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Agency Email</label>
                          <input name="agencyEmail" value={formData.agencyEmail} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                        <div>
                          <label className="block text-sm font-medium text-gray-700">Agency Phone</label>
                          <input name="agencyPhone" value={formData.agencyPhone} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm" />
                        </div>
                      </div>

                      <div className="flex justify-end pt-6 gap-2 border-t mt-6">
                        <button type="button" onClick={() => setActiveTab('project')} className="px-4 py-2 text-gray-600 hover:text-gray-900">Back</button>
                        <button
                          type="submit"
                          disabled={creating}
                          className="bg-brand-600 text-white px-6 py-2 rounded shadow-sm hover:bg-brand-700 flex items-center gap-2 font-medium disabled:opacity-50"
                        >
                          <Send size={18} /> {creating ? 'Generating PDF...' : 'Create & Send Agreement'}
                        </button>
                      </div>
                    </div>
                  )}
                </form>
              </div>
            </div>
          </div >
        )
      }

      {
        view === 'settings' && (
          <div className="max-w-3xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
              <h3 className="text-xl font-bold text-gray-900">Agent Profile Settings</h3>
              <button onClick={() => setView('list')} className="text-gray-500 hover:text-gray-700">Cancel</button>
            </div>

            <div className="bg-white shadow rounded-lg p-8">
              <h4 className="text-lg font-medium text-gray-900 mb-6">Profile Signature</h4>

              <div className="flex flex-col md:flex-row gap-8 items-start">
                <div className="flex-1 space-y-4">
                  <p className="text-sm text-gray-600">
                    Upload your signature image to be automatically included in documents you generate.
                    For best results, use a PNG image with a transparent background.
                  </p>

                  <div className="mt-4">
                    <label className="block text-sm font-medium text-gray-700 mb-2">Upload Signature</label>
                    <div className="flex items-center gap-4">
                      <label className="cursor-pointer bg-white border border-gray-300 rounded-md shadow-sm px-4 py-2 inline-flex items-center justify-center text-sm font-medium text-gray-700 hover:bg-gray-50">
                        <Upload size={16} className="mr-2" />
                        Choose File
                        <input type="file" className="hidden" accept="image/png,image/jpeg" onChange={handleSignatureUpload} />
                      </label>
                      <span className="text-xs text-gray-500">Max 2MB. PNG/JPG</span>
                    </div>
                  </div>
                </div>

                <div className="w-full md:w-1/2 flex justify-center">
                  <div className="border-2 border-dashed border-gray-300 rounded-lg p-4 w-full h-48 flex items-center justify-center bg-gray-50 relative overflow-hidden">
                    {tempSignature ? (
                      <img src={tempSignature} alt="Signature Preview" className="max-h-full max-w-full object-contain" />
                    ) : (
                      <div className="text-center text-gray-400">
                        <ImageIcon size={48} className="mx-auto mb-2 opacity-50" />
                        <span className="text-sm">No signature uploaded</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-6 border-t flex justify-end">
                <button
                  onClick={saveProfile}
                  disabled={isUploading}
                  className="bg-brand-600 text-white px-6 py-2 rounded shadow-sm hover:bg-brand-700 flex items-center gap-2 font-medium disabled:opacity-50"
                >
                  <Save size={18} /> {isUploading ? 'Saving...' : 'Save Profile'}
                </button>
              </div>
            </div>

            {/* Email Test Section */}
            <div className="bg-white shadow rounded-lg p-8 mt-6">
              <h4 className="text-lg font-medium text-gray-900 mb-4">Test Email Service</h4>
              <p className="text-sm text-gray-600 mb-4">
                Send a test email to verify your SMTP configuration.
              </p>
              <div className="flex gap-4 items-end">
                <div className="flex-1">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Target Email</label>
                  <input
                    type="email"
                    placeholder="Enter email to test..."
                    id="test-email-input"
                    className="block w-full border border-gray-300 rounded p-2 text-sm"
                  />
                </div>
                <button
                  onClick={async () => {
                    const input = document.getElementById('test-email-input') as HTMLInputElement;
                    if (!input?.value) return alert('Please enter an email');
                    try {
                      await AuthAPI.testEmail(input.value);
                      alert('Test email sent. Check your inbox (and spam folder).');
                    } catch (e: any) {
                      alert('Failed to send: ' + e.message);
                    }
                  }}
                  className="bg-gray-800 text-white px-4 py-2 rounded hover:bg-gray-700 h-10"
                >
                  Send Test Email
                </button>
              </div>
            </div>
          </div>
        )
      }

    </Layout >
  );
}
