import React, { useState, useEffect } from 'react';
import Layout from '../components/Layout';
import { User, DocumentData, DocumentStatus } from '../types';
import { createDocument, getDocuments } from '../services/storage';
import { generateBasePdf } from '../services/pdfService';
import { Plus, Send, User as UserIcon, Briefcase, FileText, Settings, Upload, Image as ImageIcon, Save, RefreshCw, Clock, CheckCircle, ArrowLeft } from 'lucide-react';
import { DocumentsAPI, AuthAPI } from '../services/api';
import { COMPANY_NAME, COMPANY_EMAIL } from '../constants'; // Added AuthAPI
import AgreementTemplates, { AgreementTemplate, availableTemplates } from '../components/AgreementTemplates';
import SupportDocumentsTable from '../components/SupportDocumentsTable';
import SupportCopyLinkModal from '../components/SupportCopyLinkModal';
import SupportResentLinkModal from '../components/SupportResentLinkModal';

interface Props {
  user: User;
  onLogout: () => void;
}

export default function SupportDashboard({ user, onLogout }: Props) {
  const [localUser, setLocalUser] = useState<User>(user); // Local copy of user for profile updates
  const [docs, setDocs] = useState<any[]>([]);
  const [view, setView] = useState<'list' | 'create' | 'settings'>('list'); // Added 'settings' view
  const [activeTab, setActiveTab] = useState<'template' | 'client' | 'project' | 'agency' | 'services'>('template');
  const [selectedTemplate, setSelectedTemplate] = useState<AgreementTemplate | null>(null);

  // Form State
  const [formData, setFormData] = useState({
    // Document Meta
    title: '',

    // Client Info
    clientName: '',
    clientCompany: '',
    clientEmail: '',
    clientPhone: '',
    clientAddress: '',
    clientCityStateZip: '',
    clientCountry: '',

    // Project Info
    projectName: '',
    startDate: '',
    endDate: '',
    scopeOfWork: '',
    paymentTerms: '',
    specialNotes: '',

    // Agency Info
    agencyName: COMPANY_NAME,
    agencyEmail: COMPANY_EMAIL,
    agencyPhone: '',

    // Template-specific fields (US Brand Booster)
    clientCompanyName: '',
    businessOwnerName: '',
    clientDomain: '',
    upfrontPayment: '350',
    remainingPayment: '650',
    serviceOverviewDetails: `- Tailored Content: Unique content aligned with your business nature and target audience.
- Geographic Targeting: Optimize Google Guarantee for specific cities of your choice, expanding your local reach – rely on chosen list of zip codes of the supplied services. The customer will supply a list.
- Complete Website (10 Page website): Standard set of the pages and the galleries of the services on top.
- ROI Reports: Receive monthly reports on the return on investment (ROI) generated by the US BB marketing efforts. Partner with US BB on a flexible, transparent basis with no contracts or hidden fees.`,
    servicesInScopeDetails: `- Create the Mockup pages for the Commercial Remodeling Contractors verification and approval. Supply 3 reviews before uploading the live pages to the Web.
- US BB will assist in creating the Google Business account.
- As soon as the Web-Site is created a 3 months Web SEO free service will start
- The US BB and the Commercial Remodeling Contractors should agree on the monthly payment for the following services:
- Facebook Maintenance and support, like posts and pictures upload activities
- Instagram – uploading the pictures and videos
- Web-site pictures and videos uploads
- Changing the keywords every period of time.
- Creating the landing pages on the Commercial Remodeling Contractors domain
- US BB will create a Facebook Dedicated page and apply the ownership to Commercial Remodeling Contractors. US BB will create 1000 facebook followers
- US BB will create the Instagram dedicated account for Commercial Remodeling Contractors. US BB will create 1300 insta followers + 1 month social media. After 1 month social media platforms will be charged.
- The US BB will upload any pictures and videos related to construction supplied by the Commercial Remodeling Contractors to Website, Facebook, Instagram.
- All the Credentials of all the accounts will be defined with the agreement by the Commercial Remodeling Contractors, including the usernames and passwords.`,
  });

  const [creating, setCreating] = useState(false);
  const [copiedLink, setCopiedLink] = useState<string | null>(null);
  const [isCopyModalOpen, setIsCopyModalOpen] = useState(false);
  const [isResentModalOpen, setIsResentModalOpen] = useState(false);
  const [resendingId, setResendingId] = useState<string | null>(null);

  const load = async () => {
    try {
      const resp = await DocumentsAPI.list();
      const serverDocs = resp.documents || [];
      const ownerId = String(localUser.id);
      const ownedServerDocs = serverDocs.filter((d: any) => {
        const docAgentId = String(d.agentId || '');
        const metaAgentId = String(d?.metadata?.agentId || '');
        return docAgentId === ownerId || metaAgentId === ownerId;
      });
      setDocs(
        ownedServerDocs
          .sort((a: any, b: any) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime())
      );
    } catch (e) {
      console.error('[SupportDashboard] load() failed', e);
      setDocs([]);
    }
  };

  useEffect(() => {
    load();
    const onFocus = () => load();
    window.addEventListener('focus', onFocus);
    const interval = setInterval(load, 10000); // poll every 10s
    return () => {
      window.removeEventListener('focus', onFocus);
      clearInterval(interval);
    };
  }, [user.id, view]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const validateForm = () => {
    if (!formData.clientEmail.endsWith('@gmail.com')) {
      alert('Client email must be a valid @gmail.com address for secure signing.');
      return false;
    }
    if (!formData.title || !formData.clientName || !formData.projectName) {
      alert('Please fill in required fields (Title, Client Name, Project Name)');
      return false;
    }
    return true;
  };

  const handleCreateDocument = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!validateForm()) return;
    setCreating(true);

    try {
      // 1. Generate PDF Base64
      const result = await generateBasePdf({
        ...formData,
        agentId: localUser.id,
        agentName: localUser.name,
        agentSignature: localUser.signature, // Pass signature
      });
      const pdfBase64 = result.pdf;

      // 2. Create on backend
      const payload: any = {
        title: formData.title,
        description: formData.scopeOfWork || undefined,
        fileUrl: pdfBase64,
        // clientId omitted -> backend will find/create by email
        metadata: {
          agentId: localUser.id,
          agentName: localUser.name,
          agentSignature: localUser.signature,
          clientName: formData.clientName,
          clientEmail: formData.clientEmail,
          clientCompany: formData.clientCompany,
          clientPhone: formData.clientPhone,
          clientAddress: formData.clientAddress,
          projectName: formData.projectName,
          startDate: formData.startDate || undefined,
          endDate: formData.endDate || undefined,
          scopeOfWork: formData.scopeOfWork || undefined,
          paymentTerms: formData.paymentTerms || undefined,
          specialNotes: formData.specialNotes || undefined,
          agencyName: formData.agencyName,
          agencyEmail: formData.agencyEmail,
          agencyPhone: formData.agencyPhone || undefined,
          // Template information
          templateId: selectedTemplate?.id || undefined,
          templateName: selectedTemplate?.name || undefined,
          // Template-specific fields (US Brand Booster)
          clientCompanyName: formData.clientCompanyName || undefined,
          businessOwnerName: formData.businessOwnerName || undefined,
          clientDomain: formData.clientDomain || undefined,
          upfrontPayment: formData.upfrontPayment || undefined,
          remainingPayment: formData.remainingPayment || undefined,
          serviceOverviewDetails: formData.serviceOverviewDetails || undefined,
          servicesInScopeDetails: formData.servicesInScopeDetails || undefined,
        }
      };

      const resp = await DocumentsAPI.create(payload);
      const created = resp.document;

      // 3. Update state from backend
      setDocs([created, ...docs]);
      setView('list');

      // Reset form to defaults
      setFormData({
        title: '',
        clientName: '',
        clientCompany: '',
        clientEmail: '',
        clientPhone: '',
        clientAddress: '',
        clientCityStateZip: '',
        clientCountry: '',
        projectName: '',
        startDate: '',
        endDate: '',
        scopeOfWork: '',
        paymentTerms: '',
        specialNotes: '',
        agencyName: COMPANY_NAME,
        agencyEmail: COMPANY_EMAIL,
        agencyPhone: '',
        clientCompanyName: '',
        businessOwnerName: '',
        clientDomain: '',
        upfrontPayment: '350',
        remainingPayment: '650',
      });
      setSelectedTemplate(null);
      setActiveTab('template');
    } catch (err) {
      console.error(err);
      alert("Error creating document. Please try again.");
    } finally {
      setCreating(false);
    }
  };

  const copyLink = async (docOrId: any) => {
    const backendId = String(typeof docOrId === 'string' ? docOrId : (docOrId._id || docOrId.id));
    let token = typeof docOrId === 'string' ? undefined : docOrId.signToken;
    // If token missing, try to refetch document; if still missing, trigger resend to generate a new token
    if (!token && backendId) {
      try {
        const resp = await DocumentsAPI.get(backendId);
        token = resp?.document?.signToken;
        if (!token) {
          await DocumentsAPI.resend(backendId);
          const after = await DocumentsAPI.get(backendId);
          token = after?.document?.signToken;
        }
      } catch { }
    }
    const base = `${window.location.origin}/sign/${backendId}`;
    const url = token ? `${base}?token=${token}` : base;
    navigator.clipboard.writeText(url);
    setCopiedLink(url);
    setIsCopyModalOpen(true);
  };

  const resendLink = async (doc: DocumentData) => {
    const backendId = String((doc as any)._id || (doc as any).id);
    setResendingId(backendId);
    try {
      await DocumentsAPI.resend(backendId);
      setIsResentModalOpen(true);
    } catch (e: any) {
      alert(`Failed to resend link: ${e?.message || 'Unknown error'}`);
    } finally {
      setResendingId(null);
    }
  };

  // Profile / Settings Logic
  const [tempSignature, setTempSignature] = useState<string>('');
  const [isUploading, setIsUploading] = useState(false);

  useEffect(() => {
    if (view === 'settings' && localUser.signature) {
      setTempSignature(localUser.signature);
    }
  }, [view, localUser.signature]);

  const handleSignatureUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    // Validate size (e.g. max 2MB)
    if (file.size > 2 * 1024 * 1024) {
      alert('File size must be less than 2MB');
      return;
    }

    const reader = new FileReader();
    reader.onload = (evt) => {
      const result = evt.target?.result as string;

      // Validate dimensions
      const img = new Image();
      img.onload = () => {
        if (img.width < 100 || img.height < 50) {
          alert('Image resolution is too low. Please upload a larger image.');
          return;
        }
        const ratio = img.width / img.height;
        if (ratio < 1 || ratio > 10) {
          alert('Image aspect ratio is unusual (too tall or too wide). please use an image that is roughly 3:1 or 4:1 width to height.');
          return;
        }
        setTempSignature(result);
      };
      img.onerror = () => {
        alert('Invalid image file.');
      };
      img.src = result;
    };
    reader.readAsDataURL(file);
  };

  const saveProfile = async () => {
    setIsUploading(true);
    try {
      await AuthAPI.updateProfile({ signature: tempSignature });
      setLocalUser({ ...localUser, signature: tempSignature });
      alert('Profile updated successfully!');
      setView('list');
    } catch (e: any) {
      alert(`Failed to save profile: ${e?.message}`);
    } finally {
      setIsUploading(false);
    }
  };

  return (
    <Layout user={user} onLogout={onLogout} title="Support Workspace">

      {view === 'list' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="card p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center"><FileText size={18} className="text-brand-600" /></div>
              <div><p className="text-xs text-brand-500 font-medium">Total</p><p className="text-2xl font-bold text-brand-900 tabular-nums">{docs.length}</p></div>
            </div>
            <div className="card p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-yellow-50 flex items-center justify-center"><Clock size={18} className="text-yellow-600" /></div>
              <div><p className="text-xs text-brand-500 font-medium">Pending</p><p className="text-2xl font-bold text-brand-900 tabular-nums">{docs.filter(d => String(d.status).toLowerCase() !== 'signed').length}</p></div>
            </div>
            <div className="card p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-green-50 flex items-center justify-center"><CheckCircle size={18} className="text-green-600" /></div>
              <div><p className="text-xs text-brand-500 font-medium">Signed</p><p className="text-2xl font-bold text-brand-900 tabular-nums">{docs.filter(d => String(d.status).toLowerCase() === 'signed').length}</p></div>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3">
            <h3 className="text-lg font-semibold text-brand-900">Your Documents</h3>
            <div className="flex items-center gap-2 flex-wrap">
              <button onClick={load} className="btn btn-secondary btn-sm">
                <RefreshCw size={14} /> Refresh
              </button>
              <button onClick={() => setView('settings')} className="btn btn-secondary btn-sm">
                <Settings size={14} /> Settings
              </button>
              <button onClick={() => setView('create')} className="btn btn-primary">
                <Plus size={16} /> New Document
              </button>
            </div>
          </div>

          <SupportDocumentsTable
            docs={docs}
            onCopyLink={copyLink}
            onResendLink={resendLink}
            resendingId={resendingId}
          />

          <SupportResentLinkModal
            isOpen={isResentModalOpen}
            onClose={() => setIsResentModalOpen(false)}
          />

          <SupportCopyLinkModal
            isOpen={isCopyModalOpen}
            link={copiedLink}
            onClose={() => {
              setIsCopyModalOpen(false);
              setCopiedLink(null);
            }}
          />
        </div>
      )}
      {
        view === 'create' && (
          <div>
            <div className="flex items-center gap-3 mb-6">
              <button onClick={() => setView('list')} className="btn btn-ghost btn-sm">
                <ArrowLeft size={16} /> Back
              </button>
              <h3 className="text-xl font-bold text-brand-900">Create Agreement</h3>
            </div>

            <div className="card overflow-hidden flex flex-col md:flex-row">
              <div className="w-full md:w-56 bg-brand-50/80 border-r border-brand-100 p-3 flex flex-col gap-1">
                {([
                  { id: 'template' as const, label: 'Template', icon: FileText },
                  { id: 'services' as const, label: 'Services', icon: FileText, disabled: !selectedTemplate },
                  { id: 'client' as const, label: 'Client', icon: UserIcon },
                  { id: 'project' as const, label: 'Project', icon: FileText },
                  { id: 'agency' as const, label: 'Agency', icon: Briefcase },
                ]).map((tab) => (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    disabled={tab.disabled}
                    className={`flex items-center gap-2.5 px-3 py-2.5 rounded-lg text-sm font-medium transition-all ${
                      activeTab === tab.id
                        ? 'bg-white text-brand-900 shadow-sm border border-brand-100'
                        : 'text-brand-500 hover:text-brand-700 hover:bg-white/60 disabled:opacity-40'
                    }`}
                  >
                    <tab.icon size={16} /> {tab.label}
                  </button>
                ))}
              </div>

              {/* Form Content */}
              <div className="flex-1 p-6">
                <form onSubmit={handleCreateDocument} className="space-y-6">

                  {activeTab === 'template' && (
                    <div className="space-y-4 animate-fadeIn">
                      <AgreementTemplates
                        selectedTemplate={selectedTemplate}
                        onSelectTemplate={(template) => {
                          setSelectedTemplate(template);
                          // Auto-fill title if template is selected
                          if (template && !formData.title) {
                            setFormData({ ...formData, title: template.name });
                          }
                        }}
                      />

                      {selectedTemplate && selectedTemplate.id === 'us-brand-booster' && (
                        <div className="mt-6 space-y-4">
                          <h4 className="text-lg font-medium border-b pb-2">Template-Specific Fields</h4>
                          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <div className="md:col-span-2">
                              <label className="label">Client Company Name *</label>
                              <input
                                name="clientCompanyName"
                                required
                                value={formData.clientCompanyName}
                                onChange={handleInputChange}
                                placeholder="e.g. Commercial Remodeling Contractors"
                                className="input-field"
                              />
                            </div>
                            <div className="md:col-span-2">
                              <label className="label">Business Owner Name *</label>
                              <input
                                name="businessOwnerName"
                                required
                                value={formData.businessOwnerName}
                                onChange={handleInputChange}
                                placeholder="e.g. David Rozenstein"
                                className="input-field"
                              />
                            </div>
                            <div className="md:col-span-2">
                              <label className="label">Client Domain Name *</label>
                              <input
                                name="clientDomain"
                                required
                                value={formData.clientDomain}
                                onChange={handleInputChange}
                                placeholder="e.g. commercialremodelingcontractors.com"
                                className="input-field"
                              />
                            </div>
                            <div>
                              <label className="label">Upfront Payment ($) *</label>
                              <input
                                name="upfrontPayment"
                                type="number"
                                required
                                value={formData.upfrontPayment}
                                onChange={handleInputChange}
                                placeholder="350"
                                className="input-field"
                              />
                            </div>
                            <div>
                              <label className="label">Remaining Payment ($) *</label>
                              <input
                                name="remainingPayment"
                                type="number"
                                required
                                value={formData.remainingPayment}
                                onChange={handleInputChange}
                                placeholder="650"
                                className="input-field"
                              />
                            </div>
                          </div>
                        </div>
                      )}

                      <div className="flex justify-end pt-4">
                        <button type="button" onClick={() => setActiveTab('services')} className="btn btn-dark" disabled={!selectedTemplate}>
                          Next: Service Details
                        </button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'services' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Service Details</h4>
                  <p className="text-sm text-brand-500 mb-4">Edit the bullet points below. Each line will be treated as a bullet point in the generated PDF.</p>

                      <div>
                        <label className="label">Service Overview</label>
                        <textarea
                          name="serviceOverviewDetails"
                          rows={8}
                          value={formData.serviceOverviewDetails}
                          onChange={handleInputChange}
                          className="input-field font-mono"
                          placeholder="- Item: Description"
                        />
                      </div>

                      <div>
                        <label className="label">Services in Scope</label>
                        <textarea
                          name="servicesInScopeDetails"
                          rows={8}
                          value={formData.servicesInScopeDetails}
                          onChange={handleInputChange}
                          className="input-field font-mono"
                          placeholder="- Item description"
                        />
                      </div>

                      <div className="flex justify-end pt-4">
                        <button type="button" onClick={() => setActiveTab('client')} className="btn btn-dark">
                          Next: Client Information
                        </button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'client' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Client Information</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                          <label className="label">Full Name *</label>
                          <input name="clientName" required value={formData.clientName} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">Company Name</label>
                          <input name="clientCompany" value={formData.clientCompany} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">Gmail Address (Required) *</label>
                          <input name="clientEmail" type="email" required value={formData.clientEmail} onChange={handleInputChange} placeholder="example@gmail.com" className="input-field" />
                        </div>
                        <div>
                          <label className="label">Phone Number</label>
                          <input name="clientPhone" value={formData.clientPhone} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div className="md:col-span-2">
                          <label className="label">Address</label>
                          <input name="clientAddress" value={formData.clientAddress} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">City / State / Zip</label>
                          <input name="clientCityStateZip" value={formData.clientCityStateZip} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">Country</label>
                          <input name="clientCountry" value={formData.clientCountry} onChange={handleInputChange} className="input-field" />
                        </div>
                      </div>
                      <div className="flex justify-end pt-4">
                        <button type="button" onClick={() => setActiveTab('project')} className="btn btn-dark">Next: Project Details</button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'project' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Project & Terms</h4>
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="md:col-span-2">
                          <label className="label">Document Title / Type *</label>
                          <input name="title" required value={formData.title} onChange={handleInputChange} placeholder="e.g. Service Agreement, NDA" className="input-field" />
                        </div>
                        <div className="md:col-span-2">
                          <label className="label">Project Name *</label>
                          <input name="projectName" required value={formData.projectName} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">Start Date</label>
                          <input name="startDate" type="date" value={formData.startDate} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">End / Delivery Date</label>
                          <input name="endDate" type="date" value={formData.endDate} onChange={handleInputChange} className="input-field" />
                        </div>

                        <div className="md:col-span-2">
                          <label className="label">
                            Scope of Work / Description
                          </label>
                          <textarea name="scopeOfWork" rows={5} value={formData.scopeOfWork} onChange={handleInputChange} className="input-field" />
                        </div>

                        <div className="md:col-span-2">
                          <label className="label">Payment Terms</label>
                          <textarea name="paymentTerms" rows={3} value={formData.paymentTerms} onChange={handleInputChange} placeholder="e.g. 50% upfront, 50% on completion" className="input-field" />
                        </div>

                        <div className="md:col-span-2">
                          <label className="label">Special Notes / Clauses</label>
                          <textarea name="specialNotes" rows={3} value={formData.specialNotes} onChange={handleInputChange} className="input-field" />
                        </div>
                      </div>
                      <div className="flex justify-end pt-4 gap-2">
                        <button type="button" onClick={() => setActiveTab('client')} className="btn btn-ghost">Back</button>
                        <button type="button" onClick={() => setActiveTab('agency')} className="btn btn-dark">Next: Agency Info</button>
                      </div>
                    </div>
                  )}

                  {activeTab === 'agency' && (
                    <div className="space-y-4 animate-fadeIn">
                      <h4 className="text-lg font-medium border-b pb-2 mb-4">Agency Information</h4>
                      <div className="grid grid-cols-1 gap-4">
                        <div>
                          <label className="label">Service Provider (Company)</label>
                          <input name="agencyName" value={formData.agencyName} onChange={handleInputChange} className="mt-1 block w-full border border-gray-300 rounded p-2 text-sm bg-gray-50" readOnly />
                        </div>
                        <div>
                          <label className="label">Support Name</label>
                          <input disabled value={user.name} className="mt-1 block w-full border border-gray-200 bg-gray-50 rounded p-2 text-sm text-gray-500" />
                          <span className="text-xs text-gray-400">Auto-filled from login</span>
                        </div>
                        <div>
                          <label className="label">Agency Email</label>
                          <input name="agencyEmail" value={formData.agencyEmail} onChange={handleInputChange} className="input-field" />
                        </div>
                        <div>
                          <label className="label">Agency Phone</label>
                          <input name="agencyPhone" value={formData.agencyPhone} onChange={handleInputChange} className="input-field" />
                        </div>
                      </div>

                      <div className="flex justify-end pt-6 gap-2 border-t border-brand-100 mt-6">
                        <button type="button" onClick={() => setActiveTab('project')} className="btn btn-ghost">Back</button>
                        <button type="submit" disabled={creating} className="btn btn-primary">
                          <Send size={16} /> {creating ? 'Generating PDF...' : 'Create & Send'}
                        </button>
                      </div>
                    </div>
                  )}
                </form>
              </div>
            </div>
          </div >
        )
      }

      {
        view === 'settings' && (
          <div className="max-w-3xl mx-auto space-y-6">
            <div className="flex items-center gap-3">
              <button onClick={() => setView('list')} className="btn btn-ghost btn-sm">
                <ArrowLeft size={16} /> Back
              </button>
              <h3 className="text-xl font-bold text-brand-900">Profile Settings</h3>
            </div>

            <div className="card">
              <div className="card-body p-6 md:p-8">
              <h4 className="text-base font-semibold text-brand-900 mb-6">Profile Signature</h4>

              <div className="flex flex-col md:flex-row gap-8 items-start">
                <div className="flex-1 space-y-4">
                  <p className="text-sm text-brand-500">
                    Upload your signature image to be automatically included in documents you generate.
                    For best results, use a PNG image with a transparent background.
                  </p>

                  <div className="mt-4">
                    <label className="label">Upload Signature</label>
                    <div className="flex items-center gap-4">
                      <label className="cursor-pointer btn btn-secondary">
                        <Upload size={16} />
                        Choose File
                        <input type="file" className="hidden" accept="image/png,image/jpeg" onChange={handleSignatureUpload} />
                      </label>
                      <span className="text-xs text-brand-400">Max 2MB · PNG/JPG</span>
                    </div>
                  </div>
                </div>

                <div className="w-full md:w-1/2 flex justify-center">
                  <div className="border-2 border-dashed border-brand-200 rounded-xl p-4 w-full h-48 flex items-center justify-center bg-brand-50 relative overflow-hidden">
                    {tempSignature ? (
                      <img src={tempSignature} alt="Signature Preview" className="max-h-full max-w-full object-contain" />
                    ) : (
                      <div className="text-center text-brand-400">
                        <ImageIcon size={40} className="mx-auto mb-2 opacity-50" />
                        <span className="text-sm">No signature uploaded</span>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-6 border-t border-brand-100 flex justify-end">
                <button onClick={saveProfile} disabled={isUploading} className="btn btn-primary">
                  <Save size={16} /> {isUploading ? 'Saving...' : 'Save Profile'}
                </button>
              </div>
              </div>
            </div>

            <div className="card">
              <div className="card-body p-6 md:p-8">
              <h4 className="text-base font-semibold text-brand-900 mb-4">Test Email Service</h4>
              <p className="text-sm text-brand-500 mb-4">
                Send a test email to verify your SMTP configuration.
              </p>
              <div className="flex flex-col gap-4">
                <div>
                  <label className="label">Document</label>
                  <select
                    id="test-email-doc"
                    className="input-field"
                    defaultValue={docs[0]?.id || ''}
                  >
                    {docs.length === 0 ? (
                      <option value="">No documents available</option>
                    ) : (
                      docs.map((d) => (
                        <option key={d.id} value={d.id}>{d.title} ({d.metadata?.clientName || 'Client'})</option>
                      ))
                    )}
                  </select>
                </div>
                <div className="flex gap-4 items-end">
                  <div className="flex-1">
                    <label className="label">Target Email</label>
                    <input
                      type="email"
                      placeholder="Enter email to test..."
                      id="test-email-input"
                      className="input-field"
                    />
                  </div>
                  <button
                    onClick={async () => {
                      const input = document.getElementById('test-email-input') as HTMLInputElement;
                      const docSelect = document.getElementById('test-email-doc') as HTMLSelectElement;
                      if (!input?.value) return alert('Please enter an email');
                      if (!docSelect?.value) return alert('Please select a document');
                      try {
                        await AuthAPI.testEmail(input.value, docSelect.value);
                        alert('Test email sent. Check your inbox (and spam folder).');
                      } catch (e: any) {
                        alert('Failed to send: ' + e.message);
                      }
                    }}
                    className="btn btn-dark h-10"
                    disabled={docs.length === 0}
                  >
                    Send Test Email
                  </button>
                </div>
              </div>
              </div>
            </div>
          </div>
        )
      }

    </Layout >
  );
}
