import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

const transporter = nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: Number(process.env.SMTP_PORT),
    // Gmail: secure true for 465 (SSL), false for ports like 587 (STARTTLS)
    secure: true,
    auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
    }
});
console.log("Password", process.env.SMTP_PASS)
export const sendAgreementEmail = async (
    to: string,
    agentEmail: string,
    agentName: string,
    clientName: string,
    title: string,
    linkUrl: string
) => {
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
        console.warn('SMTP credentials missing. Skipping email sending.');
        return;
    }

    const subject = `Agreement Created: ${title} - ${clientName}`;
    const html = `
    <div style="font-family: Arial, sans-serif; color: #333;">
      <h2 style="color: #004e7c;">New Agreement Generated</h2>
      <p>Dear ${clientName},</p>
      <p>A new agreement <strong>"${title}"</strong> has been generated by ${agentName}.</p>
      <p>Please click the secure link below to review and sign the document:</p>
      <p>
        <a href="${linkUrl}" style="display:inline-block;padding:10px 16px;background:#facc15;color:#000;text-decoration:none;border-radius:4px;font-weight:bold;">
          Open Secure Document
        </a>
      </p>
      <p style="font-size: 12px; color: #777; margin-top: 16px;">
        If the button does not work, copy and paste this URL into your browser:<br/>
        <a href="${linkUrl}">${linkUrl}</a>
      </p>
      <br/>
      <p><strong>Created Date:</strong> ${new Date().toLocaleDateString()}</p>
      <br/>
      <hr/>
      <p style="font-size: 12px; color: #777;">
        Sent via SignDesk | US Brand Booster LLC<br/>
        Authorized Agent: ${agentName} (${agentEmail})
      </p>
    </div>
  `;

    try {
        const info = await transporter.sendMail({
            from: `"${agentName}" <${process.env.SMTP_USER}>`, // Send AS the system auth user, but with Agent's name. Reply-To can be agent.
            replyTo: agentEmail,
            to,
            cc: agentEmail,
            subject,
            html,
        });

        console.log('Email sent successfully:', info.messageId);
        return info;
    } catch (error) {
        console.error('Error sending email:', error);
        // Don't throw, just log, so we don't block the API response
    }
};
